# Generated by Django 5.2.4 on 2025-07-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='favorites',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
