# Generated by Django 5.2.4 on 2025-07-19 05:27

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_appuser_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='avatarUrl',
        ),
        migrations.AddField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(default='/users/default-avatar.jpg', upload_to=server.models.unique_avatar_image_path),
        ),
    ]
