# Generated by Django 5.2.4 on 2025-09-25 16:34

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_appuser_avatarurl_appuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='cover',
            field=models.ImageField(default='volumes/covers/default-cover.webp', upload_to=server.models.unique_cover_image_path),
        ),
    ]
